services:
  mongodb:
    image: mongo:7.0.8
    container_name: sports-mongodb
    restart: always
    ports:
      - "27017-27019:27017-27019"
    environment:
      - MONGO_INITDB_DATABASE=sports
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongo-root-user
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo-root-pass
    volumes:
      - ./database/dev/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./database/dev/mongo-root-user:/run/secrets/mongo-root-user:ro
      - ./database/dev/mongo-root-pass:/run/secrets/mongo-root-pass:ro
      - mongodbdata:/data/db
    networks:
      - devnetwork

  backend:
    image: sports-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      CHOKIDAR_USEPOLLING: "true"
    env_file:
      - ./backend/.env.development.local
    ports:
      - 5050:5050
    command: npm run dev
    volumes:
      - ./backend/src:/home/app/src
    networks:
      - devnetwork

  frontend:
    image: sports-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - mongodb
      - backend
    ports:
      - 4200:4200
      - 49153:49153
    command: npm start
    volumes:
      - ./frontend/src:/home/app/src
    networks:
      - devnetwork

volumes:
  mongodbdata:
    driver: local

networks:
  devnetwork:
