services:
  mongodb-test:
    image: mongo:7.0.8
    container_name: sports-mongodb-test
    restart: always
    ports:
      - "27020-27022:27017-27019"
    environment:
      - MONGO_INITDB_DATABASE=tests
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongo-root-user
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo-root-pass
    volumes:
      - ./database/test/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./database/test/mongo-root-user:/run/secrets/mongo-root-user:ro
      - ./database/test/mongo-root-pass:/run/secrets/mongo-root-pass:ro
      - mongodbtestdata:/data/db
    networks:
      - testnetwork

volumes:
  mongodbtestdata:
    driver: local

networks:
  testnetwork:
